common:
    multi_lidar: true
    lid_topic:  "/livox/lidar_192_158_1_110"
    lid_topic2:  "/livox/lidar"
    imu_topic:  "/livox/imu_192_158_1_110"
    time_sync_en: false         # ONLY turn on when external time synchronization is really not possible
    map_frame: "map"
    
preprocess:
    lidar_type: 1                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 
    lidar_type2: 1                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 
    scan_line: 1
    scan_line2: 1
    timestamp_unit: 3                 # 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
    timestamp_unit2: 3                 # 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
    blind: 1.2
    blind2: 0.8
    point_filter_num: 3
    point_filter_num2: 3

mapping:
    acc_cov: 0.1
    gyr_cov: 0.1
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    det_range:     250.0
    extrinsic_est_en:  false  #not supported yet for multi # true: enable the online estimation of IMU-LiDAR extrinsic    
    extrinsic_T: [ 0.0, 0.0, 0.0 ]
    extrinsic_R: [1, 0, 0,
                  0, 1, 0,
                  0, 0, 1]
    extrinsic_T2: [ 0.011, 0.023, -0.044 ]
    extrinsic_R2: [1, 0, 0,
                  0, 1, 0,
                  0, 0, 1]

filter_size_map: 0.4 #bigger voxel size
adaptive:
    adaptive_voxelization_en: false # If true, ADA-FAST-LIO2, or just FAST-LIO2
    filter_size_map_smaller: 0.3 # It should be smaller than `filter_size_map`
    neighbor_xy_thres: 5.0 # xy neighbor threshold
    num_thr_adaptive_voxelization: 800
    num_thr_adaptive_voxelization_neighbor: 400


publish:
    path_en:  true
    scan_publish_en:  true       # false: close all the point cloud output
    dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

pcd_save:
    pcd_save_en: false
    interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
