map_frame: "map"                            # publish frame
loop_detection_radius: 15.0                 # unit [meter] within this radius, check if loop or not
loop_detection_timediff_threshold: 5.0      # unit [sec] check if two keyframes are loop if times are farther than this
keyframe_threshold: 1.0                     # unit [meter] every this distance, generate keyframe
gicp_score_threshold: 1.0                   # lower is more accurate